# Generated by Django 4.0.3 on 2022-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('SelectDoctor', models.CharField(max_length=50)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
