# Generated by Django 4.0.3 on 2022-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Comment',
            field=models.CharField(max_length=50),
        ),
    ]
