# Generated by Django 4.0.3 on 2022-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_approvedreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedreq',
            name='Time',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Time',
            field=models.TextField(max_length=30),
        ),
    ]
